#!/usr/bin/env bash

##
# Loop wrap: sync/enable a systemd --user unit for a long-running make entry.
#
# Gated helpers respect ASC_MONITORING / ASC_LOOP_MONITOR. Warns when linger is
# unavailable (reboot survival requires loginctl enable-linger).
#
# @param 1 String : make entry point name (e: prefix optional).
#
# @example
#   make loop-wrap e:blueprint-generate
#   asc/loop/loop.wrap.sh blueprint-generate
#

. asc/bootstrap.sh

a_entry="${1:-}"
shift || true
a_entry="${a_entry#e:}"

if [[ -z "$a_entry" ]]; then
  echo >&2 "Usage: asc/loop/loop.wrap.sh <make-entry> [args...]"
  exit 1
fi

# Resolve make entry → script path.
make_entries_arr=()
real_scripts_arr=()
f_make_list_entry_points
a_script=''
for index in "${!make_entries_arr[@]}"; do
  if [[ "${make_entries_arr[index]}" == "$a_entry" ]]; then
    a_script="${real_scripts_arr[index]}"
    break
  fi
done

if [[ -z "$a_script" || ! -f "$a_script" ]]; then
  echo >&2 "Error: unknown make entry '$a_entry'."
  exit 1
fi

a_args="$*"
# Stable instance id: entry + short hash of args (when present).
a_instance="$a_entry"
if [[ -n "$a_args" ]]; then
  a_hash="$(printf '%s' "$a_args" | sha256sum | awk '{print $1}')"
  a_instance="${a_entry}-${a_hash:0:8}"
fi

f_loop_warn_linger() {
  if ! command -v loginctl >/dev/null 2>&1; then
    echo >&2 "Warning: loginctl missing; loop unit may not survive logout."
    return 0
  fi
  local linger
  linger="$(loginctl show-user "${SUDO_USER:-$(id -un)}" -p Linger --value 2>/dev/null || echo no)"
  case "$linger" in
    yes|YES|1) ;;
    *)
      echo >&2 "Warning: user linger is off — reboot/logout survival needs: loginctl enable-linger"
      ;;
  esac
}

f_loop_wrap_enabled_monitor() {
  case "${ASC_MONITORING:-1}" in 0|false|FALSE|off|OFF) return 1 ;; esac
  case "${ASC_LOOP_MONITOR:-1}" in 0|false|FALSE|off|OFF) return 1 ;; esac
  return 0
}

if ! command -v systemctl >/dev/null 2>&1; then
  echo >&2 "Error: systemctl not available; cannot loop-wrap."
  exit 1
fi

if ! systemctl --user status >/dev/null 2>&1; then
  echo >&2 "Error: systemd user bus unavailable; cannot loop-wrap."
  exit 1
fi

f_loop_warn_linger
mkdir -p data/asc/loop "$HOME/.config/systemd/user"

unit_name="asc-loop@${a_instance}.service"
unit_path="$HOME/.config/systemd/user/${unit_name}"

# Template instance unit (simple ExecStart → make -C PROJECT_DOCROOT entry args).
exec_start="/usr/bin/make -C $(printf '%q' "${PROJECT_DOCROOT:-$PWD}") ${a_entry}"
if [[ -n "$a_args" ]]; then
  exec_start+=" ${a_args}"
fi

cat > "$unit_path" <<EOF
[Unit]
Description=ASC loop ${a_instance}
After=default.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_DOCROOT:-$PWD}
ExecStart=${exec_start}
Restart=on-failure
RestartSec=5
Environment=ASC_WRAP_NONINTERACTIVE=1
Environment=ASC_LOOP_INSTANCE=${a_instance}

[Install]
WantedBy=default.target
EOF

# Registry for loop-status / CRUD.
cat > "data/asc/loop/${a_instance}.sh" <<EOF
#!/usr/bin/env bash
# Generated by loop/wrap — do not hand-edit as SoT.
export ASC_LOOP_INSTANCE='${a_instance}'
export ASC_LOOP_ENTRY='${a_entry}'
export ASC_LOOP_ARGS='${a_args}'
export ASC_LOOP_UNIT='${unit_name}'
export ASC_LOOP_UNIT_PATH='${unit_path}'
export ASC_LOOP_RESTART='on-failure'
EOF

systemctl --user daemon-reload
systemctl --user enable --now "$unit_name"

echo "Loop started: $unit_name"
echo "  entry  : $a_entry $a_args"
echo "  unit   : $unit_path"
echo "  status : make loop-status e:$a_instance  (or systemctl --user status $unit_name)"

if f_loop_wrap_enabled_monitor; then
  hook_ms 'dry-run' -s 'loop' -a 'monitor' \
    -v 'STACK_VERSION PROVISION_USING HOST_TYPE HOST_OS' || true
  if [[ -n "${most_specific_match:-}" && -f "$most_specific_match" ]]; then
    # shellcheck disable=SC1090
    . "$most_specific_match" "$a_instance" || true
  fi
fi
